// File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel3\refModel3_dpi_pkg.sv
// Created: 2020-09-29 16:54:02
// Generated by MATLAB 9.7 and HDL Verifier 6.0

`timescale 1ns / 1ns
package refModel3_dpi_pkg;



// Declare imported C functions
import "DPI-C" function chandle DPI_refModel3_initialize(input chandle existhandle);
import "DPI-C" function chandle DPI_refModel3_reset(input chandle objhandle,input bit signed [12:0] inputMatrix_bit [3584],input bit signed [12:0] inputCent_bit [56],input bit signed [12:0] inputThreshold_bit,input bit [12:0] inputFirstPoint_bit,input bit [12:0] inputLastPoint_bit,output bit signed [12:0] finalCent_bit [56]);
import "DPI-C" function void DPI_refModel3(input chandle objhandle,input bit signed [12:0] inputMatrix_bit [3584],input bit signed [12:0] inputCent_bit [56],input bit signed [12:0] inputThreshold_bit,input bit [12:0] inputFirstPoint_bit,input bit [12:0] inputLastPoint_bit,output bit signed [12:0] finalCent_bit [56]);


import "DPI-C" function void DPI_refModel3_terminate(input chandle existhandle);






endpackage : refModel3_dpi_pkg
