/*

*File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel3\refModel3_dpi.c
*Created: 2020-10-29 17:51:21
*Generated by MATLAB 9.7 and HDL Verifier 6.0

*/

#include "refModel3.h"
#include "refModel3_dpi.h"
#include <string.h>



void get13BitBy56ArrayFromSignedCData(svBitVecVal * SVBitData,short CData[56])
{
short	idx;
for(idx=0;idx<56;idx++)
{

SVBitData[idx]=(svBitVecVal)CData[idx]&0x00001FFF;

}
}
void getSignedCDataFrom13Bit(short* CData,const svBitVecVal * SVBitData)
{
short TempData;
TempData=((*SVBitData)&0x00001000)!=0 ? (short)(((short)(*SVBitData&0x00001FFF)) | 0xFFFFE000) : (short)(*SVBitData&0x00001FFF);
memcpy(CData,&TempData,sizeof(short));
}
void getSignedCDataFrom13By3584BitArray(short CData[3584],const svBitVecVal * SVBitData)
{
short TempData;
short	idx;
for(idx=0;idx<3584;idx++)
{
TempData=((SVBitData[idx])&0x00001000)!=0 ? (short)(((short)(SVBitData[idx]&0x00001FFF)) | 0xFFFFE000) : (short)(SVBitData[idx]&0x00001FFF);
memcpy(&CData[idx],&TempData,sizeof(short));

}}
void getSignedCDataFrom13By56BitArray(short CData[56],const svBitVecVal * SVBitData)
{
short TempData;
short	idx;
for(idx=0;idx<56;idx++)
{
TempData=((SVBitData[idx])&0x00001000)!=0 ? (short)(((short)(SVBitData[idx]&0x00001FFF)) | 0xFFFFE000) : (short)(SVBitData[idx]&0x00001FFF);
memcpy(&CData[idx],&TempData,sizeof(short));

}}
void getUnsignedCDataFrom13Bit(unsigned short* CData,const svBitVecVal * SVBitData)
{
unsigned short TempData;
TempData=(unsigned short)(*SVBitData&0x00001FFF);
memcpy(CData,&TempData,sizeof(unsigned short));
}


DPI_DLL_EXPORT void * DPI_refModel3_initialize(void* existhandle)
{
    
    refModel3_initialize();
    existhandle=NULL;
    return NULL;
    
}

DPI_DLL_EXPORT void * DPI_refModel3_reset(void* objhandle,svBitVecVal * inputMatrix_bit,svBitVecVal * inputCent_bit,svBitVecVal * inputThreshold_bit,svBitVecVal * inputFirstPoint_bit,svBitVecVal * inputLastPoint_bit,svBitVecVal * finalCent_bit)
{
    DPI_refModel3_terminate(objhandle);
    objhandle=NULL;
    objhandle=DPI_refModel3_initialize(NULL);
    DPI_refModel3(objhandle,inputMatrix_bit,inputCent_bit,inputThreshold_bit,inputFirstPoint_bit,inputLastPoint_bit,finalCent_bit);
    DPI_refModel3_terminate(objhandle);
    objhandle=NULL;
    return DPI_refModel3_initialize(NULL);
    
}

DPI_DLL_EXPORT void DPI_refModel3(void* objhandle,svBitVecVal * inputMatrix_bit,svBitVecVal * inputCent_bit,svBitVecVal * inputThreshold_bit,svBitVecVal * inputFirstPoint_bit,svBitVecVal * inputLastPoint_bit,svBitVecVal * finalCent_bit)
{
    short finalCent[56];
    short inputCent[56];
    unsigned short inputFirstPoint;
    unsigned short inputLastPoint;
    short inputMatrix[3584];
    short inputThreshold;
    
    getSignedCDataFrom13By56BitArray(inputCent,inputCent_bit);
    getUnsignedCDataFrom13Bit(&inputFirstPoint,inputFirstPoint_bit);
    getUnsignedCDataFrom13Bit(&inputLastPoint,inputLastPoint_bit);
    getSignedCDataFrom13By3584BitArray(inputMatrix,inputMatrix_bit);
    getSignedCDataFrom13Bit(&inputThreshold,inputThreshold_bit);
    
    refModel3(inputMatrix,inputCent,inputThreshold,inputFirstPoint,inputLastPoint,finalCent); 
     objhandle=NULL; 
    
    get13BitBy56ArrayFromSignedCData(finalCent_bit,finalCent);
    
    
}

DPI_DLL_EXPORT void DPI_refModel3_terminate(void* existhandle)
{
    existhandle=NULL;
    refModel3_terminate();
    
}
