// File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel3\refModel3_dpi.sv
// Created: 2020-09-29 16:54:02
// Generated by MATLAB 9.7 and HDL Verifier 6.0

`timescale 1ns / 1ns

import refModel3_dpi_pkg::*;



module refModel3_dpi(
    input bit clk,
    input bit clk_enable,
    input bit reset,
    input bit signed [12:0] inputMatrix_bit [0:3583],
    input bit signed [12:0] inputCent_bit [0:55],
    input bit signed [12:0] inputThreshold_bit,
    input bit [12:0] inputFirstPoint_bit,
    input bit [12:0] inputLastPoint_bit,
    output bit signed [12:0] finalCent_bit [0:55]
);

    chandle objhandle=null;
    
    bit signed [12:0] finalCent_bit_temp [0:55];
    
    

    initial begin
        objhandle=DPI_refModel3_initialize(objhandle);
    end

    final begin
        DPI_refModel3_terminate(objhandle);
    end

    always @(posedge clk or posedge reset) begin
        if(reset== 1'b1) begin
            objhandle=DPI_refModel3_reset(objhandle,inputMatrix_bit,inputCent_bit,inputThreshold_bit,inputFirstPoint_bit,inputLastPoint_bit,finalCent_bit_temp);
            finalCent_bit<=finalCent_bit_temp;
            
        end
        else if(clk_enable) begin
            DPI_refModel3(objhandle,inputMatrix_bit,inputCent_bit,inputThreshold_bit,inputFirstPoint_bit,inputLastPoint_bit,finalCent_bit_temp);
            
            finalCent_bit<=finalCent_bit_temp;
            
            
            
            
        end
    end
endmodule
