// File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel2\refModel2_dpi_pkg.sv
// Created: 2020-09-01 09:44:50
// Generated by MATLAB 9.7 and HDL Verifier 6.0

`timescale 1ns / 1ns
package refModel2_dpi_pkg;



// Declare imported C functions
import "DPI-C" function chandle DPI_refModel2_initialize(input chandle existhandle);
import "DPI-C" function chandle DPI_refModel2_reset(input chandle objhandle,input bit signed [12:0] inputMatrix_bit [3584],input bit signed [12:0] inputCent_bit [56],output bit signed [12:0] finalCent_bit [56]);
import "DPI-C" function void DPI_refModel2(input chandle objhandle,input bit signed [12:0] inputMatrix_bit [3584],input bit signed [12:0] inputCent_bit [56],output bit signed [12:0] finalCent_bit [56]);


import "DPI-C" function void DPI_refModel2_terminate(input chandle existhandle);






endpackage : refModel2_dpi_pkg
