// File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel2\refModel2_dpi.sv
// Created: 2020-08-25 17:41:28
// Generated by MATLAB 9.7 and HDL Verifier 6.0

`timescale 1ns / 1ns

import refModel2_dpi_pkg::*;



module refModel2_dpi(
    input bit clk,
    input bit clk_enable,
    input bit reset,
    input bit signed [12:0] inputMatrix_bit [0:3583],
    input bit signed [12:0] inputCent_bit [0:55],
    output bit signed [12:0] finalCent_bit [0:55]
);

    chandle objhandle=null;
    
    bit signed [12:0] finalCent_bit_temp [0:55];
    
    

    initial begin
        objhandle=DPI_refModel2_initialize(objhandle);
    end

    final begin
        DPI_refModel2_terminate(objhandle);
    end

    always @(posedge clk or posedge reset) begin
        if(reset== 1'b1) begin
            objhandle=DPI_refModel2_reset(objhandle,inputMatrix_bit,inputCent_bit,finalCent_bit_temp);
            finalCent_bit<=finalCent_bit_temp;
            
        end
        else if(clk_enable) begin
            DPI_refModel2(objhandle,inputMatrix_bit,inputCent_bit,finalCent_bit_temp);
            
            finalCent_bit<=finalCent_bit_temp;
            
            
            
            
        end
    end
endmodule
