// File: C:\Users\liora.000\Documents\Semester summer 2020\UVM_project\Matlab scripts\codegen\dll\refModel2\refModel2_dpi_pkg.sv
// Created: 2020-08-18 11:28:42
// Generated by MATLAB 9.7 and HDL Verifier 6.0

`timescale 1ns / 1ns
package refModel2_dpi_pkg;



// Declare imported C functions
import "DPI-C" function chandle DPI_refModel2_initialize(input chandle existhandle);
import "DPI-C" function chandle DPI_refModel2_reset(input chandle objhandle,input shortint inputMatrix [3584],input shortint inputCent [56],output shortint finalCent [56]);
import "DPI-C" function void DPI_refModel2(input chandle objhandle,input shortint inputMatrix [3584],input shortint inputCent [56],output shortint finalCent [56]);


import "DPI-C" function void DPI_refModel2_terminate(input chandle existhandle);






endpackage : refModel2_dpi_pkg
